Implement `__delitem__` method for base Settings (#1191)
* test(base): add del item tests

Add some cases to test_deleted_raise in
test_base to check that deleting an item
through the __delitem__ operator works
as expected. However, since the operator
is not available in the base Settings
class, the test shall fail.

The exception thrown looks something like:
```
Unexpected exception occurred!
Traceback (most recent call last):
...
  File "/venv/lib64/python3.12/site-packages/dynaconf/utils/functional.py", line 19, in inner
    return func(self._wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: __delitem__
```

Signed-off-by: Albert Esteve <aesteve@redhat.com>

* fix(base): add __delitem__ method to Settings

Add support for deleting items by keyword, by
adding the __delitem__ method to the Settings
class.

This way, users may delete items by doing:
```
del settings["my_key"]
```

As a counterpart to delete only by attribute.

Signed-off-by: Albert Esteve <aesteve@redhat.com>

---------

Signed-off-by: Albert Esteve <aesteve@redhat.com>